### ISSUE TITLE
java 17 m1 support

### ISSUE THREAD

**Issue by ArchieGoodwin** [Picovoice/picovoice#230]
After successful compile of java library I am getting this in debug and tests: 

Caused by: java.lang.RuntimeException: Porcupine failed to get get CPU information.
	at ai.picovoice.porcupine.Utils.getCpuPart(Utils.java:195)
	at ai.picovoice.porcupine.Utils.getArchitecture(Utils.java:163)
	at ai.picovoice.porcupine.Utils.&lt;clinit&gt;(Utils.java:41)
	... 78 more

### Steps to reproduce the behaviour

Compile library on macOS 12 on Mac with Apple Silicon CPU

**Comment by ksyeo1010** [comment]
We are currently working on it for java 17 and gradle 7.3, which at the time gradle didnt support java 17 build which is the java version with support for mac m1. For now, if you would like work with mac m1 and java, consider using java 11 which should work with m1.

**Comment by ErisMik** [comment]
@ArchieGoodwin The latest versions of our Java packages now have Java 17+ and native Mac M1 support. Feel free to open another ticket if more issues arise.
