### ISSUE TITLE
Cannot run demos on  Raspberry PI 4

### ISSUE THREAD

**Issue by hackebike** [Picovoice/picovoice#27]
I downloaded the SDk on my Raspberry PI 4 running Raspberry pi OS 64 bit kernel 5.10.
I am trying to use the demo but I am getting an error:

**python3 test_picovoice.py** 
Traceback (most recent call last):
  File "test_picovoice.py", line 18, in <module>
    import pvporcupine
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/__init__.py", line 13, in <module>
    from .util import *
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/util.py", line 54, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/util.py", line 47, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/util.py", line 24, in _pv_linux_machine
    model_info = [x for x in cpu_info.split('\n') if 'model name' in x][0]
IndexError: list index out of range

Also I would like to use Picovoice with the ReSpeaker 4-Mic Array for Raspberry Pi and if I launch the **picovoice_respeaker_demo** I get a similar error:

~ $ picovoice_respeaker_demo 
Traceback (most recent call last):
  File "/usr/local/bin/picovoice_respeaker_demo", line 6, in <module>
    from pvrespeakerdemo.picovoice_demo import main
  File "/usr/local/lib/python3.7/dist-packages/pvrespeakerdemo/__init__.py", line 13, in <module>
    from .picovoice_demo import PicovoiceDemo
  File "/usr/local/lib/python3.7/dist-packages/pvrespeakerdemo/picovoice_demo.py", line 19, in <module>
    from picovoice import Picovoice
  File "/usr/local/lib/python3.7/dist-packages/picovoice/__init__.py", line 12, in <module>
    from .picovoice import Picovoice
  File "/usr/local/lib/python3.7/dist-packages/picovoice/picovoice.py", line 14, in <module>
    import pvporcupine
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/__init__.py", line 13, in <module>
    from .util import *
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/util.py", line 54, in <module>
    _PV_SYSTEM, _PV_MACHINE = _pv_platform()
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/util.py", line 47, in _pv_platform
    pv_machine = _pv_linux_machine(platform.machine())
  File "/usr/local/lib/python3.7/dist-packages/pvporcupine/util.py", line 24, in _pv_linux_machine
    model_info = [x for x in cpu_info.split('\n') if 'model name' in x][0]
IndexError: list index out of range

Am I missing something? I followed this [post](https://wiki.seeedstudio.com/ReSpeaker_4_Mic_Array_for_Raspberry_Pi/#enabling-voice-recognition-at-edge-with-picovoice) until I get to the picovoice everything worked.

**Comment by kenarsa** [comment]
If you run with the official 32-bit OS it will work out of the box

**Comment by hackebike** [comment]
So you do not support Raspberry pi OS 64 bit? Any plans?

**Comment by kenarsa** [comment]
The current intention is to support the official RPI OS which is 32-bit at this time. Correct me if I'm wrong, please. When they switch to 64-bit OS we will support that as well.

**Comment by hackebike** [comment]
great, there is a 64 bit beta OS at the moment.
