### ISSUE TITLE
Picovoice Issue: PicovoiceActivationError on RPi Buster

### ISSUE THREAD

**Issue by creating-worlds** [Picovoice/picovoice#298]
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
Run initialization without any error

### Actual behaviour
With my code

```
import time
import sys
from picovoice import Picovoice

class VoiceAgent():

    def __init__(
        self,
        access_key="********************************************"):

        self.handle = Picovoice(
            access_key=access_key,
            keyword_path="/path/to/wakeword.ppn",
            wake_word_callback=self.__wake_word_callback,
            context_path="/path/to/context.rhn",
            inference_callback=self.__inference_callback)
                    
    def __wake_word_callback(self):
        print("Wake up Word detected ")

    def __inference_callback(self, inference):
        print("Inference detected")
        print(inference)


if __name__ == "__main__":

    voice_agent = VoiceAgent()
    print("starting voice agent")
```

I get

```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/picovoice/picovoice.py", line 185, in __init__
    self._porcupine = pvporcupine.create(
  File "/home/pi/.local/lib/python3.9/site-packages/pvporcupine/__init__.py", line 77, in create
    return Porcupine(
  File "/home/pi/.local/lib/python3.9/site-packages/pvporcupine/porcupine.py", line 158, in __init__
    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()
pvporcupine.porcupine.PorcupineActivationError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/script.py", line 30, in <module>
    voice_agent = VoiceAgent()
  File "/path/to/script.py", line 13, in __init__
    self.handle = Picovoice(
  File "/home/pi/.local/lib/python3.9/site-packages/picovoice/picovoice.py", line 192, in __init__
    raise _PPN_RHN_ERROR_TO_PICOVOICE_ERROR[type(e)] from e
picovoice.picovoice.PicovoiceActivationError
```

Picovoice console shows 0/3 connected devices

### Steps to reproduce the behaviour

```
RaspberryPi 4 model B
Raspbian Buster Lite
Python 3.9.10
Picovoice V2.1
AccessKey created via Picovoice Console
.ppn file and .rhn accessible
```

Installed via
`python3 -m pip install picovoice`

Script run without sudo (modules installed locally)

**Comment by kenarsa** [comment]
do you have internet connectivity?

**Comment by creating-worlds** [comment]
Do I need internet connection? I thought this service would work offline.

**Comment by kenarsa** [comment]
You do periodic internet connections for AccessKey validation.

**Comment by creating-worlds** [comment]
Alright, works like a charm now. Thank you!
