### ISSUE TITLE
Picovoice Issue: dotnet demo message Microsoft Windows 10.0.17763 (X64) is not currently supported.

### ISSUE THREAD

**Issue by FDer12** [Picovoice/picovoice#329]
Dear,

in the readme seems that picovoice supports both Windows 32 and 64  bit systems.   

extract readme

Cross-Platform: Design once, deploy anywhere. Build using familiar languages and frameworks.
Arm Cortex-M, STM32, PSoC, Arduino, and i.MX RT
Raspberry Pi, NVIDIA Jetson Nano, and BeagleBone
Android and iOS
Chrome, Safari, Firefox, and Edge
Linux (x86_64), macOS (x86_64, arm64), and Windows (x86_64)

However when I'm running the dotnet demo I get following error

Pv.PicovoiceException: Microsoft Windows 10.0.17763 (X64) is not currently supported.
Visit https://picovoice.ai/docs/api/porcupine-dotnet/ to see a list of supported platforms.
 ---> System.PlatformNotSupportedException: Microsoft Windows 10.0.17763 (X64) is not currently supported.
Visit https://picovoice.ai/docs/api/porcupine-dotnet/ to see a list of supported platforms.
   at Pv.Utils.PvLibraryPath(String libName)
   at Pv.Porcupine.ImportResolver(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Pv.Porcupine.pv_porcupine_init(String accessKey, String modelPath, Int32 numKeywords, String[] keywordPaths, Single[] sensitivities, IntPtr& handle)
   at Pv.Porcupine..ctor(String accessKey, IEnumerable`1 keywordPaths, String modelPath, IEnumerable`1 sensitivities)
   at Pv.Porcupine.FromKeywordPaths(String accessKey, IEnumerable`1 keywordPaths, String modelPath, IEnumerable`1 sensitivities)
   at Pv.Picovoice.Create(String accessKey, String keywordPath, Action wakeWordCallback, String contextPath, Action`1 inferenceCallback, String porcupineModelPath, Single porcupineSensitivity, String rhinoModelPath, Single rhinoSensitivity, Boolean requireEndpoint)

**Comment by laves** [comment]
closed due to inactivity

**Comment by FDer12** [comment]
Dear Ian,

Sorry for my late answer,

Indeed when I build for x64 platform,  I can get the program working.

***@***.***


In theory the target machine will be a touch panel Windows 32 bit. So I assume the dotnet demo will not run on that machine  since 32 architecture isn’t supported ?


***@***.***
I also already experimented with the web demo, that seems to function as well.  I hope if the dotnet option doesn’t work,  that I can do the job with the web variant

Regards

Frank



***@***.***
Frank ***@***.***>
***@***.***<https://www.bmsvision.com/?utm_source=email&utm_medium=logo&utm_campaign=FDR>
Project Manager
