### ISSUE TITLE
Picovoice Service demo not supported on Android API 31+

### ISSUE THREAD

**Issue by RezaS** [Picovoice/picovoice#332]
In Android, I am using Picovoice as a service. In Emulator, my app is working perfectly fine. Now I have built an APK file and use this in my real Samsung Galaxy device. In general, the app works fine, but whenever I try to start the Picovoice Service, the app will crash.

This is how I start the service:

```java
mDialog.startService(getContext()); // <-- App only crashes when I use this line
```

```java
public void startService(Context context) {
    mServiceIntent = new Intent(context, PicovoiceService.class);
    mServiceIntent.putExtra("keywordFileName", "Hey-Ki_de_android_v2_1_0.ppn");
    mServiceIntent.putExtra("contextFileName", "Ki_de_android_v2_1_0.rhn");
    ContextCompat.startForegroundService(context, mServiceIntent);
}
```
How comes that in emulator the service works fine but the app crashes on real devices? 
Console shows me that the Device Limits are 2 of 3.

**Comment by kenarsa** [comment]
what do you see in the log? there should be error messages ...

**Comment by RezaS** [comment]
When debugging my device, this is the error that I get:

> 2022-04-02 22:41:18.584 16611-16611/? E/USNET: USNET: appName: ch.yourclick.ki
2022-04-02 22:41:19.546 16611-16611/ch.yourclick.ki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ch.yourclick.ki, PID: 16611
    java.lang.RuntimeException: Unable to start service ch.yourclick.ki.services.PicovoiceService@d2ab860 with Intent { cmp=ch.yourclick.ki/.services.PicovoiceService (has extras) }: java.lang.IllegalArgumentException: ch.yourclick.ki: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
        at android.app.ActivityThread.access$2200(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: java.lang.IllegalArgumentException: ch.yourclick.ki: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
        at android.app.PendingIntent.getActivity(PendingIntent.java:451)
        at android.app.PendingIntent.getActivity(PendingIntent.java:415)
        at ch.yourclick.ki.services.PicovoiceService.getNotification(PicovoiceService.java:142)
        at ch.yourclick.ki.services.PicovoiceService.onStartCommand(PicovoiceService.java:127)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
        	... 9 more

When my app starts, it will automatically set the mode to _Do Not Disturb_. Could that be the issue?

**Comment by laves** [comment]
@RezaS - from that error log, it seems you are not passing the correct arguments to your service:
```console
Caused by: java.lang.IllegalArgumentException: ch.yourclick.ki: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```
As this does not appear to be an problem with the Picovoice SDK, I'm going to close this issue. Feel free to reopen if you find that it is indeed an issue with our SDK.

**Comment by RezaS** [comment]
The problem was the method `getNotification()` in [PicovoiceService.java](https://github.com/Picovoice/picovoice/blob/master/demo/android/Service/picovoice-service-demo-app/src/main/java/ai/picovoice/picovoicedemoservice/PicovoiceService.java).

The last parameter should be `PendingIntent.FLAG_MUTABLE`, instead of `0`. I have now changed it to the following and it works fine:

```java
PendingIntent pendingIntent = null;
if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.S) {
    pendingIntent = PendingIntent.getActivity(
            this,
            0,
            new Intent(this, MainActivity.class),
            PendingIntent.FLAG_MUTABLE);
}
```

**Comment by laves** [comment]
Apologies @RezaS, it does seem as though you've uncovered a bug in our demo related to Android version 31 or higher. We'll address this in the coming days.

**Comment by mrrostam** [comment]
Fixed, thank you for the report!
