### ISSUE TITLE
Picovoice issue when running demo on python with Raspberry Pi 4

### ISSUE THREAD

**Issue by opesam** [Picovoice/picovoice#333]
Hello i am attempting to run the pico voice demo to test my custom wakeword and rhino but i am running into an issue. I am using a Respeaker USB mic array connected to the Pi via USB. The console error is below:
picovoice_demo_mic --access_key == --keyword_path /home/pi/Desktop/hey-lazy-suzan.ppn --context_path /home/pi/Desktop/lazy-2_en_raspberry-pi_v2_1_0.rhn

Using device: ReSpeaker 4 Mic Array (UAC1.0) Multichannel
[Listening ...]
Traceback (most recent call last):
  File "/home/pi/.local/bin/picovoice_demo_mic", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/picovoicedemo/picovoice_demo_mic.py", line 212, in main
    PicovoiceDemo(
  File "/home/pi/.local/lib/python3.9/site-packages/picovoicedemo/picovoice_demo_mic.py", line 124, in run
    pcm = recorder.read()
  File "/home/pi/.local/lib/python3.9/site-packages/pvrecorder/pvrecorder.py", line 129, in read
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to read from device.")
OSError: Failed to read from device.

**Comment by mrrostam** [comment]
It seems the demo cannot read from the default audio device. 

Can you please:

1. Verify that the Respeaker USB mic array is working fine (this [link](https://www.hifiberry.com/docs/software/use-audacity-to-record-and-edit-sound-on-your-raspberry-pi/) might help)

2. List all the available audio devices first with:
```console
picovoice_demo_mic --show_audio_devices
```
3. Run the demo again and set the correct audio device based on the previous step' info using `--audio_device_index`

**Comment by opesam** [comment]
I did that and i think it works now. However i got no output. I used the picovoice console to develop custom porcupine and rhino. i am trying to test it on raspberry pi and i don't know how to

**Comment by mrrostam** [comment]
ok, can you also store the recorded audio using `--output_path` and listen to it to make sure that the audio stream sending to the engine has no issue?

**Comment by opesam** [comment]
I got this error when i tried it

picovoice_demo_mic --access_key  --keyword_path /home/pi/Desktop/hey-lazy-suzan.ppn --context_path /home/pi/Desktop/lazy-2_en_raspberry-pi_v2_1_0.rhn --output_path /home/pi/Desktop
Traceback (most recent call last):
  File "/home/pi/.local/bin/picovoice_demo_mic", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/picovoicedemo/picovoice_demo_mic.py", line 212, in main
    PicovoiceDemo(
  File "/home/pi/.local/lib/python3.9/site-packages/picovoicedemo/picovoice_demo_mic.py", line 117, in run
    wav_file = wave.open(self.output_path, "w")
  File "/usr/lib/python3.9/wave.py", line 511, in open
    return Wave_write(f)
  File "/usr/lib/python3.9/wave.py", line 304, in __init__
    f = builtins.open(f, 'wb')
IsADirectoryError: [Errno 21] Is a directory: '/home/pi/Desktop'
Exception ignored in: <function Wave_write.__del__ at 0x7f89175430>
Traceback (most recent call last):
  File "/usr/lib/python3.9/wave.py", line 326, in __del__
    self.close()
  File "/usr/lib/python3.9/wave.py", line 443, in close
    if self._file:
AttributeError: 'Wave_write' object has no attribute '_file'

**Comment by mrrostam** [comment]
replace `--output_path /home/pi/Desktop` with `--output_path /home/pi/Desktop/test.wav` and try again

**Comment by kenarsa** [comment]
closing due to activitiy. re-open if needed

**Comment by opesam** [comment]
So i did what you said and i can hear the audio output. However it is not showing the commands on screen when i say them. or even showing that wakeword was detected
