### ISSUE TITLE
error: custom keywords and contexts not the same language

### ISSUE THREAD

**Issue by Gummi-Ente** [Picovoice/picovoice#49]
I created my custom context and keyword file (both with german language) on the Picovoice Console. Unfortunately I get the following error when using with python:

`[ERROR] context file belongs to 'de' while model file belongs to 'en'`
`Traceback (most recent call last):`
`  File "/home/me/Documents/picovoice/src/main.py", line 20, in <module>`
`    pv = Picovoice(`
`  File "/home/me/Documents/picovoice/env/lib/python3.9/site-packages/picovoice/picovoice.py", line 110, in __init__`
`    self._rhino = pvrhino.create(`
`  File "/home/me/Documents/picovoice/env/lib/python3.9/site-packages/pvrhino/__init__.py", line 42, in create`
`    return Rhino(library_path=library_path, model_path=model_path, context_path=context_path, sensitivity=sensitivity)`
`  File "/home/me/Documents/picovoice/env/lib/python3.9/site-packages/pvrhino/rhino.py", line 83, in __init__`
`    raise self._PICOVOICE_STATUS_TO_EXCEPTION[status]()`
`ValueError`

Context and keyword file a both german and custom.

Some bug or am I just stupid?

**Comment by kenarsa** [comment]
The `.PV` files are available on GitHub. For non-English languages, you need to provide them as input arguments to the constructor.

[Porcupine DE model](https://github.com/Picovoice/porcupine/blob/master/lib/common/porcupine_params_de.pv)
[Rhino DE model](https://github.com/Picovoice/rhino/blob/master/lib/common/rhino_params_de.pv)

**Comment by kenarsa** [comment]
@Gummi-Ente I'm closing this due to inactivity. If you still experience the issue above please re-open
