### ISSUE TITLE
Error on Leopard build when using custom model

### ISSUE THREAD

**Issue by Stexjy** [Picovoice/picovoice#747]
this.leopard = new Leopard.Builder()
                    .setAccessKey(accessKey)
                    .setModelPath("C:\\Users\\goost\\Documents\\Development\\Progetti\\CustomAI\\src\\main\\resources\\leopard.pv")
                    .build();

if I don't use custom model path then it works just fine

Error:
ai.picovoice.leopard.LeopardIOException: Initialization failed.
	at ai.picovoice.leopard.LeopardNative.init(Native Method)
	at ai.picovoice.leopard.Leopard.<init>(Leopard.java:54)
	at ai.picovoice.leopard.Leopard.<init>(Leopard.java:21)
	at ai.picovoice.leopard.Leopard$Builder.build(Leopard.java:231)
	at customai.speech_recognition.SpeechRecognition.instantiateLeopard(SpeechRecognition.java:30)
	at customai.speech_recognition.SpeechRecognition.<init>(SpeechRecognition.java:21)

**Comment by ErisMik** [comment]
Hi, could you please provide some additional information for your report:
- What `OS` and `OS` version are you using?
- Which programming language `SDK` are you using and what is the version of the `SDK` and the `language`?

Based off what you've given me please ensure that path to the model (`.pv`) is correct and that it's version matches the version of your `leopard` sdk.

**Comment by Stexjy** [comment]
Thanks for the reply, I didn't realize I was quite a few versions behind with the sdk. Updating it fixed everything
